### ISSUE TITLE
Styles get screwn up from time to time (maps)

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/simplechart#40]

**Comment by nasdan** [comment]
I'm researching this issue, and it looks like it doesn't load styles when navigate to a page in dev mode:

Loading page from url (dev mode):

![url_dev_mode](https://user-images.githubusercontent.com/4374977/44985751-bb21da00-af81-11e8-896b-712e2557b0e3.gif)

Loading page navigating with Link (dev mode):

_See that home page load styles because it has margin left and top._

![link_dev_mode](https://user-images.githubusercontent.com/4374977/44985766-c07f2480-af81-11e8-9c4c-8cd782112370.gif)

Loading page from url (prod mode):

![url_prod_mode](https://user-images.githubusercontent.com/4374977/44985853-19e75380-af82-11e8-9846-affbbab88a8b.gif)

Loading page navigating with Link (prod mode):

![link_prod_mode](https://user-images.githubusercontent.com/4374977/44985922-5adf6800-af82-11e8-80bb-63d7960b5acb.gif)

I didn't find any related issue with that on next or next-sass.
Did you get this issue before in any repository or sample?

**Comment by nasdan** [comment]
[Related issue](https://github.com/zeit/next-plugins/issues/282#issuecomment-432127816) on Nextjs to solve it
